# Generated by Django 5.0.6 on 2024-06-20 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w-]+$', 'Only alphanumeric characters, hyphens, and underscores are allowed.')]),
        ),
    ]
