# Generated by Django 5.0.6 on 2024-06-20 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slog_app', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.-]+$', 'Only alphanumeric characters, dots, hyphens, and underscores are allowed. Additionally max 30 chars is allowed for username.')]),
        ),
    ]
