# Generated by Django 5.0.6 on 2024-06-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slog_app', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default/default-image.png', upload_to='profile_images/'),
        ),
    ]
